using Microsoft.CodeAnalysis;
using System.Collections.Generic;

namespace CDorst.HttpApiGenerator.Builders;

internal static class RecordBuilder
{
    public static GeneratorExecutionContext AddRecordSource(this GeneratorExecutionContext context, KeyValuePair<string, string> record)
    {
        context.AddSource($"{record.Key}.cs", @$"// <auto-generated />
namespace GeneratedSource;

#nullable enable

internal {record.Value}
");
        return context;
    }

    public static GeneratorExecutionContext AddRecordSource(this GeneratorExecutionContext context, IEnumerable<KeyValuePair<string, string>> records)
    {
        foreach (var record in records)
        {
            _ = context.AddRecordSource(record);
        }
        
        return context;
    }
}
